site_name: Amstramgrame
site_description: Plateforme web du projet Amstramgrame.
copyright: Copyright &copy; 2020 <a href="http://www.grame.fr">Grame-CNCM</a> & <a href="https://www.reseau-canope.fr/">Réseau Canopé</a>
nav:
    - Parcours pédagogiques:
      - ' Hello World : mon premier programme Faust ' : scenari/hello-world.md
      - ' Faire fonctionner Hello World sur le Gramophone ' : scenari/hello-world-gramo.md
      - ' Visite guidée des exemples de programme de Gramophone ' : scenari/examples.md
      - ' Capter le geste : travailler avec l&#39;accéléromètre et le gyroscope ' : scenari/gesture.md
    - Le Gramophone:
      - ' Qu&#39;est-ce que c&#39;est ? ' : gramophone/about.md
      - ' Le GramoLoader ' : gramophone/loader.md
      - ' Programmer le Gramophone ' : gramophone/programming.md
      - ' Fabriquer le Gramophone ' : gramophone/making.md
      - ' Programmes Faust pour Gramophone ' : gramophone/programs.md
    - Faust:
      - ' Qu&#39;est-ce que c&#39;est ? ' : faust/about.md
      - ' Le Faust Web IDE ' : faust/ide.md
      - ' Le Faust Playground ' : faust/playground.md
    - À propos: about.md

theme: 
  name: mkdocs
  custom_dir: 'theme'
  navigation_depth: 4
#The available installed themes are: mkdocs, readthedocs, cinder, cosmo, flatly, spacelab, united, yeti

site_dir: ../../docs


extra:
    social:
        - type: github
          link: https://github.com/grame-cncm/amstramgrame
        - type: home
          link: https://www.amstramgrame.fr
        - type: envelope
          link: mailto:michony@grame.fr

plugins:
  - search

extra:
  search:
    language: fr

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - markdown_include.include:
        base_path: './docs'
