site_name: Amstramgrame
site_description: Web platform of the Amstramgrame project.
copyright: Copyright &copy; 2020 <a href="http://www.grame.fr">Grame-CNCM</a> & <a href="https://www.reseau-canope.fr/">Réseau Canopé</a>
nav:
    - The Gramophone:
      - ' Making the Gramophone ' : gramophone/making.md
    - Faust: https://faust.grame.fr
    - About: index.md

theme: 
  name: mkdocs
  custom_dir: 'theme'
  navigation_depth: 4
#The available installed themes are: mkdocs, readthedocs, cinder, cosmo, flatly, spacelab, united, yeti

site_dir: ../../../docs/en


extra:
    social:
        - type: github
          link: https://github.com/grame-cncm/amstramgrame
        - type: home
          link: https://www.amstramgrame.fr
        - type: envelope
          link: mailto:michon@grame.fr

plugins:
  - search

extra:
  search:
    language: en

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - markdown_include.include:
        base_path: './docs'
